apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busy1
  name: busy1
spec:
  containers:
  - image: busybox
    name: busy1
    command: ['sh', '-c', 'while true; do sleep 3600; done']
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
