apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: web
  template:
    metadata:
      labels:
        tier: web
    spec:
      containers:
      - name: nginx
        image: nginx
